# this has yet to exist but the folder will house our audio processing effects

# cmake_minimum_required(VERSION 3.22)

# set(AUDIO_DEVICES_SOURCES

# )

# set(AUDIO_DEVICES_HEADERS

# )

# add_library(AUDIO_DEVICES STATIC
#     ${AUDIO_DEVICES_HEADERS}
#     ${AUDIO_DEVICES_SOURCES}
# )

# target_include_libraries(AUDIO_DEVICES
#     PUBLIC
#         ${CAKE_CURRENT_SOURCE_DIR}
# )

# target_link_libraries(JANKI_SWEET PUBLIC AUDIO_DEVICES)